[package]
name = "bak"
version = "0.3.0"
authors = ["Anthony slab <contact@anthonyslab.org>"]
edition = "2021"

[profile.release]
opt-level = 'z' 
lto = true
codegen-units = 1
panic = 'abort'
Debug = false
strip = true
